const projects = [
    {
      id: 1,
      name: 'Task Organaizer',
      description: 'Python Flask project',
      imageUrl: 'https://picsum.photos/seed/1/300/200',
      technologies: ['Python', 'Flask', 'Javascript','css'],
      liveUrl: 'https://example.com/project1',
      codeUrl: 'https://github.com/RoniRan542/todo-list-rest-api',
    },
    {
      id: 2,
      name: 'Snake',
      description: 'C++ Snake game',
      imageUrl: 'https://picsum.photos/seed/2/300/200',
      technologies: ['C', 'C++'],
      liveUrl: 'snakeGifSmall.gif',
      codeUrl: 'https://github.com/RoniRan542/snake_cpp',
    },
    {
      id: 3,
      name: 'Checkers',
      description: 'C++ checkers game',
      imageUrl: 'https://picsum.photos/seed/3/300/200',
      technologies: ['C', 'C++'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/checkers_cpp',
    },
    {
      id: 4,
      name: 'Url-Shortener',
      description: 'Python Flask project',
      imageUrl: 'https://picsum.photos/seed/5/300/200',
      technologies: ['Python', 'Flask', 'Jinja2'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/url-shoertener-python',
    },
    {
      id: 5,
      name: 'Garage System',
      description: 'A C++ garage management system',
      imageUrl: 'https://picsum.photos/seed/6/300/200',
      technologies: ['C', 'C++', 'cppJson'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/garage_system_git',
    },
    {
      id: 6,
      name: 'Local Cloud',
      description: 'A distributed file system on external local machines using Networking protocols',
      imageUrl: 'https://picsum.photos/seed/7/300/200',
      technologies: ['C', 'C++', 'NBD','bash'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/Embedded-project',
    },
    {
      id: 7,
      name: 'Random Qoutes Machine',
      description: 'Using remote API to create a random-qoutes website',
      imageUrl: 'https://picsum.photos/seed/7/300/200',
      technologies: ['html', 'css', 'javascript'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/random-quotes-remote-api-app',
    },
    {
      id: 8,
      name: 'Task Organizer',
      description: 'A helpful task organizer built with nodeJs and ExpressJs',
      imageUrl: 'https://picsum.photos/seed/7/300/200',
      technologies: ['nodeJs', 'expressJs', 'mongoDB'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/task-organizer-node-app',
    },
    {
      id: 9,
      name: 'Facebook-like app',
      description: 'A nodeJs API that allows creating users and publishing posts (includes a simple react frontend)',
      imageUrl: 'https://picsum.photos/seed/7/300/200',
      technologies: ['nodeJs', 'expressJs', 'mongoDB','reactJs'],
      liveUrl: 'https://example.com/project3',
      codeUrl: 'https://github.com/RoniRan542/users-posts-node-app',
    },
  ];

  export default projects;